### ISSUE TITLE
Different output format

### ISSUE THREAD

**Issue by JuanIrache** [GMOD/binary-parser#12]
Hi, thanks for this fork. I was trying to use it instead of the default one, and I had to adjust to the different output format.

In binary-parser I can read the results directly by key. With this one they are nested inside .result.

Is this expected? Not a big deal, but just in case I am doing something wrong or you had not noticed.

Thanks

**Comment by cmdcolin** [comment]
Yes that is expected, it was needed to determine the size of the parsed chunks in our application. I added a little documentation to the README to help

**Comment by cmdcolin** [comment]
Thanks for checking though!

**Comment by JuanIrache** [comment]
Appreciated
